/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-10 at 07:44:20 UTC 
 * Modify at your own risk.
 */

package org.knitter.giftregistrylite.giftendpoint;

/**
 * Service definition for Giftendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GiftendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Giftendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the giftendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://giftregistrylite.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "giftendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Giftendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Giftendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getGift".
   *
   * This request holds the parameters needed by the giftendpoint server.  After setting any optional
   * parameters, call the {@link GetGift#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetGift getGift(java.lang.Long id) throws java.io.IOException {
    GetGift result = new GetGift(id);
    initialize(result);
    return result;
  }

  public class GetGift extends GiftendpointRequest<org.knitter.giftregistrylite.giftendpoint.model.Gift> {

    private static final String REST_PATH = "gift/{id}";

    /**
     * Create a request for the method "getGift".
     *
     * This request holds the parameters needed by the the giftendpoint server.  After setting any
     * optional parameters, call the {@link GetGift#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetGift#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetGift(java.lang.Long id) {
      super(Giftendpoint.this, "GET", REST_PATH, null, org.knitter.giftregistrylite.giftendpoint.model.Gift.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetGift setAlt(java.lang.String alt) {
      return (GetGift) super.setAlt(alt);
    }

    @Override
    public GetGift setFields(java.lang.String fields) {
      return (GetGift) super.setFields(fields);
    }

    @Override
    public GetGift setKey(java.lang.String key) {
      return (GetGift) super.setKey(key);
    }

    @Override
    public GetGift setOauthToken(java.lang.String oauthToken) {
      return (GetGift) super.setOauthToken(oauthToken);
    }

    @Override
    public GetGift setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetGift) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetGift setQuotaUser(java.lang.String quotaUser) {
      return (GetGift) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetGift setUserIp(java.lang.String userIp) {
      return (GetGift) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetGift setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetGift set(String parameterName, Object value) {
      return (GetGift) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertGift".
   *
   * This request holds the parameters needed by the giftendpoint server.  After setting any optional
   * parameters, call the {@link InsertGift#execute()} method to invoke the remote operation.
   *
   * @param content the {@link org.knitter.giftregistrylite.giftendpoint.model.Gift}
   * @return the request
   */
  public InsertGift insertGift(org.knitter.giftregistrylite.giftendpoint.model.Gift content) throws java.io.IOException {
    InsertGift result = new InsertGift(content);
    initialize(result);
    return result;
  }

  public class InsertGift extends GiftendpointRequest<org.knitter.giftregistrylite.giftendpoint.model.Gift> {

    private static final String REST_PATH = "gift";

    /**
     * Create a request for the method "insertGift".
     *
     * This request holds the parameters needed by the the giftendpoint server.  After setting any
     * optional parameters, call the {@link InsertGift#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertGift#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link org.knitter.giftregistrylite.giftendpoint.model.Gift}
     * @since 1.13
     */
    protected InsertGift(org.knitter.giftregistrylite.giftendpoint.model.Gift content) {
      super(Giftendpoint.this, "POST", REST_PATH, content, org.knitter.giftregistrylite.giftendpoint.model.Gift.class);
    }

    @Override
    public InsertGift setAlt(java.lang.String alt) {
      return (InsertGift) super.setAlt(alt);
    }

    @Override
    public InsertGift setFields(java.lang.String fields) {
      return (InsertGift) super.setFields(fields);
    }

    @Override
    public InsertGift setKey(java.lang.String key) {
      return (InsertGift) super.setKey(key);
    }

    @Override
    public InsertGift setOauthToken(java.lang.String oauthToken) {
      return (InsertGift) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertGift setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertGift) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertGift setQuotaUser(java.lang.String quotaUser) {
      return (InsertGift) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertGift setUserIp(java.lang.String userIp) {
      return (InsertGift) super.setUserIp(userIp);
    }

    @Override
    public InsertGift set(String parameterName, Object value) {
      return (InsertGift) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listGift".
   *
   * This request holds the parameters needed by the giftendpoint server.  After setting any optional
   * parameters, call the {@link ListGift#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListGift listGift() throws java.io.IOException {
    ListGift result = new ListGift();
    initialize(result);
    return result;
  }

  public class ListGift extends GiftendpointRequest<org.knitter.giftregistrylite.giftendpoint.model.CollectionResponseGift> {

    private static final String REST_PATH = "gift";

    /**
     * Create a request for the method "listGift".
     *
     * This request holds the parameters needed by the the giftendpoint server.  After setting any
     * optional parameters, call the {@link ListGift#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListGift#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListGift() {
      super(Giftendpoint.this, "GET", REST_PATH, null, org.knitter.giftregistrylite.giftendpoint.model.CollectionResponseGift.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListGift setAlt(java.lang.String alt) {
      return (ListGift) super.setAlt(alt);
    }

    @Override
    public ListGift setFields(java.lang.String fields) {
      return (ListGift) super.setFields(fields);
    }

    @Override
    public ListGift setKey(java.lang.String key) {
      return (ListGift) super.setKey(key);
    }

    @Override
    public ListGift setOauthToken(java.lang.String oauthToken) {
      return (ListGift) super.setOauthToken(oauthToken);
    }

    @Override
    public ListGift setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListGift) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListGift setQuotaUser(java.lang.String quotaUser) {
      return (ListGift) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListGift setUserIp(java.lang.String userIp) {
      return (ListGift) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListGift setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListGift setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListGift set(String parameterName, Object value) {
      return (ListGift) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeGift".
   *
   * This request holds the parameters needed by the giftendpoint server.  After setting any optional
   * parameters, call the {@link RemoveGift#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveGift removeGift(java.lang.Long id) throws java.io.IOException {
    RemoveGift result = new RemoveGift(id);
    initialize(result);
    return result;
  }

  public class RemoveGift extends GiftendpointRequest<Void> {

    private static final String REST_PATH = "gift/{id}";

    /**
     * Create a request for the method "removeGift".
     *
     * This request holds the parameters needed by the the giftendpoint server.  After setting any
     * optional parameters, call the {@link RemoveGift#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveGift#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveGift(java.lang.Long id) {
      super(Giftendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveGift setAlt(java.lang.String alt) {
      return (RemoveGift) super.setAlt(alt);
    }

    @Override
    public RemoveGift setFields(java.lang.String fields) {
      return (RemoveGift) super.setFields(fields);
    }

    @Override
    public RemoveGift setKey(java.lang.String key) {
      return (RemoveGift) super.setKey(key);
    }

    @Override
    public RemoveGift setOauthToken(java.lang.String oauthToken) {
      return (RemoveGift) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveGift setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveGift) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveGift setQuotaUser(java.lang.String quotaUser) {
      return (RemoveGift) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveGift setUserIp(java.lang.String userIp) {
      return (RemoveGift) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveGift setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveGift set(String parameterName, Object value) {
      return (RemoveGift) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateGift".
   *
   * This request holds the parameters needed by the giftendpoint server.  After setting any optional
   * parameters, call the {@link UpdateGift#execute()} method to invoke the remote operation.
   *
   * @param content the {@link org.knitter.giftregistrylite.giftendpoint.model.Gift}
   * @return the request
   */
  public UpdateGift updateGift(org.knitter.giftregistrylite.giftendpoint.model.Gift content) throws java.io.IOException {
    UpdateGift result = new UpdateGift(content);
    initialize(result);
    return result;
  }

  public class UpdateGift extends GiftendpointRequest<org.knitter.giftregistrylite.giftendpoint.model.Gift> {

    private static final String REST_PATH = "gift";

    /**
     * Create a request for the method "updateGift".
     *
     * This request holds the parameters needed by the the giftendpoint server.  After setting any
     * optional parameters, call the {@link UpdateGift#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateGift#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link org.knitter.giftregistrylite.giftendpoint.model.Gift}
     * @since 1.13
     */
    protected UpdateGift(org.knitter.giftregistrylite.giftendpoint.model.Gift content) {
      super(Giftendpoint.this, "PUT", REST_PATH, content, org.knitter.giftregistrylite.giftendpoint.model.Gift.class);
    }

    @Override
    public UpdateGift setAlt(java.lang.String alt) {
      return (UpdateGift) super.setAlt(alt);
    }

    @Override
    public UpdateGift setFields(java.lang.String fields) {
      return (UpdateGift) super.setFields(fields);
    }

    @Override
    public UpdateGift setKey(java.lang.String key) {
      return (UpdateGift) super.setKey(key);
    }

    @Override
    public UpdateGift setOauthToken(java.lang.String oauthToken) {
      return (UpdateGift) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateGift setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateGift) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateGift setQuotaUser(java.lang.String quotaUser) {
      return (UpdateGift) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateGift setUserIp(java.lang.String userIp) {
      return (UpdateGift) super.setUserIp(userIp);
    }

    @Override
    public UpdateGift set(String parameterName, Object value) {
      return (UpdateGift) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Giftendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Giftendpoint}. */
    @Override
    public Giftendpoint build() {
      return new Giftendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GiftendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGiftendpointRequestInitializer(
        GiftendpointRequestInitializer giftendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(giftendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
